// <auto-generated />
using Ami.Health.Core.Entities;
using Ami.Health.WebApi.Admin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ami.Health.WebApi.Admin.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20180222092330_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ami.Health.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountStatus");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<bool>("IsFirstTimeLogin");

                    b.Property<string>("NRC")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("SecurityQuestion1")
                        .HasMaxLength(50);

                    b.Property<string>("SecurityQuestion2")
                        .HasMaxLength(50);

                    b.Property<string>("SecurityQuestion3")
                        .HasMaxLength(50);

                    b.Property<string>("SecurityQuestion4")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ami.Health.WebApi.Admin.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("DateTime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Ami.Health.WebApi.Admin.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdminId");

                    b.Property<string>("LogInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<DateTime>("LoggedDate")
                        .HasColumnType("DateTime2");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Logger");
                });
#pragma warning restore 612, 618
        }
    }
}
